server:
  port: 9001

spring:
  application:
    name: nf_eureka_server

eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer2:9002/eureka/